from PySide6.QtWidgets import QWidget, QVBoxLayout, QHBoxLayout, QGridLayout, QLabel, QPushButton, QComboBox, QTableWidget, QTableWidgetItem, QTextEdit, QMessageBox
from PySide6.QtCore import Qt, QTimer
from epw_os.gui.logger import ui_logger
from epw_os.gui.table_helpers import set_resizable_columns
from epw_os.core.protection_verifier import ProtectionVerifier
from epw_os.gui.theme_manager import get_theme_manager, current_colors
from epw_os.i18n import tr

class PageEngineerMode(QWidget):
    def __init__(self, tag_manager, protection_manager, access_manager, audit_logger=None, parent=None):
        super().__init__(parent)
        self.tag_manager = tag_manager
        # Task (System.PendingCommand/System.ActiveTrip requirement #4) -
        # threaded straight through to ProtectionVerifier, which is the
        # one that actually knows WHICH precondition was denied and why.
        self.verifier = ProtectionVerifier(tag_manager, protection_manager, access_manager, audit_logger)
        
        self.verifier.log_msg.connect(self.print_term)
        self.verifier.test_finished.connect(self.on_test_finished)
        
        layout = QVBoxLayout(self)
        layout.setContentsMargins(10, 10, 10, 10)

        title = QLabel(tr("pages.engineer_mode.title"))
        title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        title.setObjectName("PageHeader")
        layout.addWidget(title)

        grid = QGridLayout()
        layout.addLayout(grid)

        grid.addWidget(QLabel(tr("pages.engineer_mode.lbl_select_protection")), 0, 0)
        self.cmb_prot = QComboBox()
        # pid/s.name are protection config identifiers, not display text -
        # left untranslated (same treatment as tag names elsewhere).
        self.cmb_prot.addItems([f"{pid} - {s.name}" for pid, p in protection_manager.protections.items() for s in p.stages])
        grid.addWidget(self.cmb_prot, 0, 1)

        self.btn_start = QPushButton(tr("pages.engineer_mode.btn_start"))
        self.btn_start.setToolTip(tr("pages.engineer_mode.tooltip_btn_start"))
        self.btn_start.clicked.connect(self.start_test)
        grid.addWidget(self.btn_start, 0, 2)

        # Output Terminal
        self.terminal = QTextEdit()
        self.terminal.setReadOnly(True)
        layout.addWidget(self.terminal, stretch=2)

        self._refresh_theme_styles()
        get_theme_manager().theme_changed.connect(self._refresh_theme_styles)

        # Reports
        reports_title = QLabel(tr("pages.engineer_mode.reports_title"))
        reports_title.setObjectName("SectionHeader")
        layout.addWidget(reports_title)

        self.table = QTableWidget(0, 5)
        self.table.setHorizontalHeaderLabels([
            tr("pages.engineer_mode.col_date"), tr("pages.engineer_mode.col_time"),
            tr("pages.engineer_mode.col_protection"), tr("pages.engineer_mode.col_result"),
            tr("pages.engineer_mode.col_operator"),
        ])
        # Date, Time, Protection, Result, Operator - all draggable.
        set_resizable_columns(self.table.horizontalHeader(), [110, 90, 320, 90, 150])
        self.table.verticalHeader().setVisible(False)
        self.table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)

        layout.addWidget(self.table, stretch=1)

        self.refresh_reports()

    def _refresh_theme_styles(self, *_):
        c = current_colors()
        self.btn_start.setStyleSheet(f"font-weight: bold; background: {c['action_danger']}; color: {c['accent_text']};")
        self.terminal.setStyleSheet(f"background: {c['lcd_bg']}; color: {c['lcd_fg']}; font-family: 'Consolas'; font-size: 12px;")

    def print_term(self, text):
        self.terminal.append(text)

    def start_test(self):
        if self.verifier.state != "IDLE":
            return
        self.terminal.clear()
        self.print_term(tr("pages.engineer_mode.term_safety_check"))

        prot_sel = self.cmb_prot.currentText()

        # `reason` is a diagnostic string generated by ProtectionVerifier
        # (core, not this page) - embedded as-is, not translated here.
        ok, reason = self.verifier.check_safety_conditions()
        if not ok:
            self.print_term(tr("pages.engineer_mode.term_test_blocked", reason=reason))
            return

        self.print_term(tr("pages.engineer_mode.term_pretest_pass"))

        # Add operator confirmation dialog
        reply = QMessageBox.question(
            self, tr("pages.engineer_mode.confirm_title"),
            tr("pages.engineer_mode.confirm_text"),
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No, QMessageBox.StandardButton.No
        )

        if reply == QMessageBox.StandardButton.Yes:
            self.verifier.start_verification(prot_sel)
        else:
            self.print_term(tr("pages.engineer_mode.term_test_aborted"))
        
    def on_test_finished(self, rep):
        # This whole report_text block (including res_char) is deliberately
        # left untranslated - see SESSION_REPORT.md's flagged-decision
        # section. It's a formal, signable verification record (rep.result
        # is itself persisted verbatim to protection_reports.json), and
        # translating only its on-screen rendering while the archived data
        # stays in English would let the same test read as pass/fail in
        # two different languages depending on which screen language was
        # active when it was viewed - the exact ambiguity the task asked
        # to be flagged rather than decided unilaterally.
        res_char = "✔ PASS" if rep.result == "PASS" else "✖ FAIL"

        report_text = f"""
--------------------------------------------------
EPW Protection Verification Report

Protection: {rep.protection}
Configured Pickup: {rep.conf_pickup}
Measured Pickup: {rep.meas_pickup}
Deviation: {0.0}  # Placeholder for diff
Configured Delay: {rep.conf_delay}
Measured Delay: {rep.meas_delay}
Output: {rep.output}
Feedback: {rep.feedback}

Verification Result
{res_char}

Engineer Comment:
______________________________
______________________________

Operator Signature:
______________________________

EPW OS Version: {rep.sw_version}
Firmware Version: {rep.fw_version}
Date: {rep.date}
Time: {rep.time}
--------------------------------------------------
"""
        self.print_term(report_text)
        self.print_term(tr("pages.engineer_mode.term_completed"))
        self.refresh_reports()

    def refresh_reports(self):
        self.table.setRowCount(0)
        for r in self.verifier.reports:
            row = self.table.rowCount()
            self.table.insertRow(row)
            self.table.setItem(row, 0, QTableWidgetItem(r.date))
            self.table.setItem(row, 1, QTableWidgetItem(r.time))
            self.table.setItem(row, 2, QTableWidgetItem(r.protection))
            item_res = QTableWidgetItem(r.result)
            if r.result == "PASS":
                item_res.setForeground(Qt.GlobalColor.green)
            else:
                item_res.setForeground(Qt.GlobalColor.red)
            self.table.setItem(row, 3, item_res)
            self.table.setItem(row, 4, QTableWidgetItem(r.operator))
