"""add intrusion alarm history table

Revision ID: 49a16c05accc
Revises: baeb133fb1f5
Create Date: 2026-09-07 16:48:53.330614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a16c05accc'
down_revision: Union[str, Sequence[str], None] = 'baeb133fb1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intrusion_alarm_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('zone_name', sa.String(), nullable=True),
    sa.Column('line_id', sa.String(), nullable=True),
    sa.Column('line_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intrusion_alarm_history_event_type'), 'intrusion_alarm_history', ['event_type'], unique=False)
    op.create_index(op.f('ix_intrusion_alarm_history_id'), 'intrusion_alarm_history', ['id'], unique=False)
    op.create_index(op.f('ix_intrusion_alarm_history_timestamp'), 'intrusion_alarm_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_intrusion_alarm_history_zone_id'), 'intrusion_alarm_history', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intrusion_alarm_history_zone_id'), table_name='intrusion_alarm_history')
    op.drop_index(op.f('ix_intrusion_alarm_history_timestamp'), table_name='intrusion_alarm_history')
    op.drop_index(op.f('ix_intrusion_alarm_history_id'), table_name='intrusion_alarm_history')
    op.drop_index(op.f('ix_intrusion_alarm_history_event_type'), table_name='intrusion_alarm_history')
    op.drop_table('intrusion_alarm_history')
    # ### end Alembic commands ###
