"""Initial typed tag schema

Revision ID: a8f45d156e3d
Revises: 
Create Date: 2026-08-21 15:05:54.509946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f45d156e3d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_id', sa.String(), nullable=True),
    sa.Column('source_tag', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('activation_time', sa.DateTime(), nullable=True),
    sa.Column('clear_time', sa.DateTime(), nullable=True),
    sa.Column('ack_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarm_history_alarm_id'), 'alarm_history', ['alarm_id'], unique=False)
    op.create_index(op.f('ix_alarm_history_id'), 'alarm_history', ['id'], unique=False)
    op.create_table('tag_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('val_bool', sa.Boolean(), nullable=True),
    sa.Column('val_int', sa.Integer(), nullable=True),
    sa.Column('val_real', sa.Float(), nullable=True),
    sa.Column('val_string', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_history_id'), 'tag_history', ['id'], unique=False)
    op.create_index(op.f('ix_tag_history_tag_name'), 'tag_history', ['tag_name'], unique=False)
    op.create_index(op.f('ix_tag_history_timestamp'), 'tag_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_history_timestamp'), table_name='tag_history')
    op.drop_index(op.f('ix_tag_history_tag_name'), table_name='tag_history')
    op.drop_index(op.f('ix_tag_history_id'), table_name='tag_history')
    op.drop_table('tag_history')
    op.drop_index(op.f('ix_alarm_history_id'), table_name='alarm_history')
    op.drop_index(op.f('ix_alarm_history_alarm_id'), table_name='alarm_history')
    op.drop_table('alarm_history')
    # ### end Alembic commands ###
