import os

# Qt's QSS border trick for drawing arrow triangles (0-size box + colored
# borders, the standard web-CSS technique) does not render reliably across
# Qt/style combinations here - it paints solid blocks instead of triangles.
# Small pre-rendered PNGs referenced via `image: url(...)` are the reliable
# alternative; see epw_os/gui/assets/ (generated by a one-off QPainter
# script, checked in as static assets) and the up/down spin arrow rules
# below. These are small black-on-transparent glyphs, not recolored per
# theme (Task: "motyw zmienia WYLACZNIE kolory" of the QSS chrome; a 9x5px
# arrow glyph is a structural asset, not a color) - every theme's panel_bg
# is deliberately kept mid-toned enough (never near-black or near-white)
# that these stay visible regardless of theme, see SESSION_REPORT.md.
_ASSETS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "assets").replace("\\", "/")

# Task: "przelaczane motywy wizualne" - every color literal below is now a
# {token} filled in from epw_os/core/themes.py's per-theme color dict by
# build_stylesheet(). Nothing else in this template changes between
# themes: same border widths, same padding, same shapes - only colors, so
# the classic Win98-NT chunky-bevel look survives in every theme (GRANICE).
_STYLE_TEMPLATE = """
/* Classic Windows NT/98 Industrial Style - colors from the active theme */

QWidget {{
    background-color: {window_bg};
    color: {text};
    font-family: "Tahoma", "MS Sans Serif", sans-serif;
    font-size: 11px;
}}

QMainWindow, QDialog, QPanel {{
    background-color: {window_bg};
}}

/* 3D Borders for frames and panels */
QFrame {{
    background-color: {panel_bg};
    border: 2px solid;
    border-top-color: {bevel_light};
    border-left-color: {bevel_light};
    border-right-color: {bevel_shadow};
    border-bottom-color: {bevel_shadow};
}}

QFrame#SunkenFrame {{
    border-top-color: {bevel_shadow};
    border-left-color: {bevel_shadow};
    border-right-color: {bevel_light};
    border-bottom-color: {bevel_light};
}}

/* Data Tables */
QTableWidget, QTreeWidget {{
    background-color: {field_bg};
    color: {text};
    border: 2px solid;
    border-top-color: {bevel_shadow};
    border-left-color: {bevel_shadow};
    border-right-color: {bevel_light};
    border-bottom-color: {bevel_light};
    gridline-color: {grid_line};
    selection-background-color: {accent_bg};
    selection-color: {accent_text};
    font-family: "Tahoma", "MS Sans Serif", sans-serif;
    font-size: 11px;
}}

QTableWidget::item, QTreeWidget::item {{
    border-bottom: 1px solid {grid_line};
    border-right: 1px solid {grid_line};
    padding: 2px;
}}

QTableWidget::item:selected, QTreeWidget::item:selected {{
    background-color: {accent_bg};
    color: {accent_text};
}}

QHeaderView::section {{
    background-color: {panel_bg};
    border: 2px outset;
    border-top-color: {bevel_light};
    border-left-color: {bevel_light};
    border-right-color: {bevel_shadow};
    border-bottom-color: {bevel_shadow};
    padding: 2px;
    font-weight: bold;
}}

/* Event Recorder Specialized Table */
QTableWidget#EventTable {{
    gridline-color: {console_bg};
    background-color: {console_bg};
    color: {console_text};
    font-family: 'Consolas', 'Courier New';
    font-size: 12px;
    border: 2px solid {console_border};
}}
QTableWidget#EventTable QHeaderView::section {{
    background-color: {console_header_bg};
    color: {console_header_text};
    border: 1px solid {console_border};
}}

/* 3D Buttons */
QPushButton {{
    background-color: {panel_bg};
    border: 2px solid;
    border-top-color: {bevel_light};
    border-left-color: {bevel_light};
    border-right-color: {button_shadow};
    border-bottom-color: {button_shadow};
    padding: 4px;
    color: {text};
}}

QPushButton:pressed {{
    border-top-color: {button_shadow};
    border-left-color: {button_shadow};
    border-right-color: {bevel_light};
    border-bottom-color: {bevel_light};
    padding-top: 5px;
    padding-left: 5px;
}}

QPushButton:disabled {{
    color: {text_disabled};
}}

/* Menus and Toolbars */
QMenuBar {{
    background-color: {panel_bg};
    border-bottom: 2px outset {bevel_light};
}}

QMenuBar::item {{
    background-color: transparent;
    padding: 2px 6px;
}}

QMenuBar::item:selected {{
    background-color: {accent_bg};
    color: {accent_text};
}}

QMenu {{
    background-color: {panel_bg};
    border: 2px outset {bevel_light};
}}

QMenu::item:selected {{
    background-color: {accent_bg};
    color: {accent_text};
}}

QToolBar {{
    background-color: {panel_bg};
    border-bottom: 2px solid;
    border-bottom-color: {bevel_shadow};
    padding: 2px;
}}

/* Status Bar */
QStatusBar {{
    background-color: {panel_bg};
    border-top: 2px solid;
    border-top-color: {bevel_light};
}}

QStatusBar::item {{
    border: 1px inset {bevel_shadow};
    padding: 2px;
}}

/* Text boxes/LCDs for industrial look */
QLabel#LCD {{
    background-color: {lcd_bg};
    color: {lcd_fg};
    border: 2px inset {bevel_shadow};
    font-weight: bold;
    font-size: 12px;
}}

/* Common Page and Section Headers */
QLabel#PageHeader {{
    font-size: 14px;
    font-weight: bold;
    background-color: {accent_bg};
    color: {accent_text};
    padding: 5px;
}}

QLabel#SectionHeader {{
    font-size: 12px;
    font-weight: bold;
    background-color: {accent_bg};
    color: {accent_text};
    padding: 2px;
}}

/* Custom Standard Dialogs */
QDialog#IndustrialDialog {{
    border: 2px solid {dialog_border};
    background-color: {panel_bg};
    font-family: "Tahoma", "MS Sans Serif", sans-serif;
}}

/* Standardized Editors */
QComboBox, QSpinBox, QDoubleSpinBox, QLineEdit {{
    background-color: {field_bg};
    color: {text};
    border: 2px inset {bevel_shadow};
    padding: 2px;
    min-height: 20px;
}}

/* Remove QComboBox::drop-down overrides to restore native/classic OS arrows that might have been hidden */

/* QSpinBox/QDoubleSpinBox lose their native up/down buttons once a custom
   border/background is applied above, so they must be redrawn explicitly
   as classic 3D-beveled stepper buttons with visible triangle arrows. */
QSpinBox, QDoubleSpinBox {{
    padding-right: 2px;
}}
QSpinBox::up-button, QDoubleSpinBox::up-button {{
    subcontrol-origin: border;
    subcontrol-position: top right;
    width: 15px;
    height: 10px;
    background-color: {panel_bg};
    border: 1px outset {bevel_light};
    border-right: none;
    border-top: none;
}}
QSpinBox::down-button, QDoubleSpinBox::down-button {{
    subcontrol-origin: border;
    subcontrol-position: bottom right;
    width: 15px;
    height: 10px;
    background-color: {panel_bg};
    border: 1px outset {bevel_light};
    border-right: none;
    border-bottom: none;
}}
QSpinBox::up-button:pressed, QDoubleSpinBox::up-button:pressed,
QSpinBox::down-button:pressed, QDoubleSpinBox::down-button:pressed {{
    background-color: {spin_pressed_bg};
}}
QSpinBox::up-button:disabled, QDoubleSpinBox::up-button:disabled,
QSpinBox::down-button:disabled, QDoubleSpinBox::down-button:disabled {{
    background-color: {window_bg};
}}
QSpinBox::up-arrow, QDoubleSpinBox::up-arrow {{
    image: url(__SPIN_UP_PNG__);
    width: 9px;
    height: 5px;
}}
QSpinBox::down-arrow, QDoubleSpinBox::down-arrow {{
    image: url(__SPIN_DOWN_PNG__);
    width: 9px;
    height: 5px;
}}
QSpinBox::up-arrow:disabled, QDoubleSpinBox::up-arrow:disabled {{
    image: url(__SPIN_UP_DISABLED_PNG__);
}}
QSpinBox::down-arrow:disabled, QDoubleSpinBox::down-arrow:disabled {{
    image: url(__SPIN_DOWN_DISABLED_PNG__);
}}

/* Alarm List */
QListWidget#AlarmBar {{
    background-color: {field_bg};
    color: {text};
    border: 2px inset {bevel_shadow};
}}
"""

_STYLE_TEMPLATE = (
    _STYLE_TEMPLATE
    .replace("__SPIN_UP_PNG__", _ASSETS_DIR + "/spin_up.png")
    .replace("__SPIN_DOWN_PNG__", _ASSETS_DIR + "/spin_down.png")
    .replace("__SPIN_UP_DISABLED_PNG__", _ASSETS_DIR + "/spin_up_disabled.png")
    .replace("__SPIN_DOWN_DISABLED_PNG__", _ASSETS_DIR + "/spin_down_disabled.png")
)


def build_stylesheet(colors: dict) -> str:
    """Renders the app-wide QSS for one theme's color dict (see
    epw_os/core/themes.py). Called once at startup and again every time
    the active theme changes (Task: "zmiana natychmiastowa, bez
    restartu") - QMainWindow.setStyleSheet() with a new string re-polishes
    every descendant widget live, no per-widget code needed for anything
    driven by this stylesheet."""
    return _STYLE_TEMPLATE.format(**colors)


# Backward-compatible constant: the Industrial theme's stylesheet, exactly
# as this module used to export it before theming existed (still the
# initial stylesheet MainWindow applies before ThemeManager takes over -
# see main_window.py). Kept as a plain, plain string (not the function)
# since several other modules/tests already import this name directly.
from epw_os.core.themes import get_theme as _get_theme  # noqa: E402

WINDOWS_NT_STYLE = build_stylesheet(_get_theme(0)["colors"])
