"""Generates studio/shell/identity/*.png and *.ico - the platform's
visual identity. Run manually (`python generate_identity.py` from this
directory) whenever the identity assets need to change; the files
themselves are committed and loaded from disk by studio/main.py (app
icon + splash) and studio/tools/register_file_type.py (file icon) -
neither regenerates them at runtime, same "script in repo, artifacts
are the source of truth" convention studio/shell/icons/generate_icons.py
and studio/shell/help/generate_help.py already established.

SOURCE: runtime/epw_os/resources/about_logo.png (READ ONLY - GRANICE:
runtime/ never touched, only read here). That file is THE official
BroniszLabs/EPW logo: a 1254x1254 pixel-art illustration - the two
mascots (ELA, diagnostics/inputs; ADA, outputs) in front of a Win98
desktop carrying the navy "EPW / ENTRY GATE SYSTEM" plaque, framed by
a circular vignette.

TWO-TIER RENDERING, and why it is not a compromise of the logo but the
standard way Windows icons work (Explorer picks a different embedded
frame per view; Windows' own shell icons are drawn differently per
size, they are not one bitmap shrunk five times):

  - LARGE sizes render the WHOLE logo. Measured on the real file,
    rendered and looked at rather than assumed (see _contact_sheet.png
    next to this script, regenerated by this same run): at 256px and
    128px every element reads - both mascots, the plaque, the side
    panels, the taskbar. At 48px the plaque still reads as a bright
    block and the mascots as two recognizable figures - the brand is
    still identifiable, which is what an icon at that size has to do.
  - SMALL sizes (16px, 32px) render the plaque crop ALONE. The full
    illustration at those sizes is genuinely unrecognizable mush -
    verified the same way, by rendering it and looking, not guessed.
    The plaque ("EPW" in bold, high-contrast, blocky lettering on
    navy) is the one element of the logo that survives that far down,
    so it is what the small frames carry. It is a crop OF the logo,
    not a substitute for it.
  - _ILLUSTRATION_MIN_PX / _FILE_INSET_MIN_PX below are those two
    thresholds. They differ because the app icon spends almost the
    whole canvas on the logo, while the file icon spends about half of
    it (the rest is the document page the badge sits on) - so a 48px
    FILE icon would shrink the logo to ~26px of actual pixels, well
    into the mush range, while a 48px APP icon gives it ~44px.

THE VIGNETTE: the logo's circular frame is an exact inscribed circle -
center (627, 627), radius 627, touching all four edges at their
midpoints. Verified by scanning the real pixels (max-channel
threshold, not luminance - the vignette's interior near the top is a
dark navy that a luminance test wrongly reads as background). The
icons re-cut that circle with an antialiased alpha mask, so the logo
lands on Explorer's background as a round badge with no black corners
instead of a black square.

STYLE, deliberately DIFFERENT from studio/shell/icons/'s own 16x16
Win98-manner toolbar set: those are hard-pixel, no-antialiasing by an
explicit, repeated instruction for THAT specific context (period-
accurate toolbar buttons). A file/app icon is a modern Windows shell
icon, rendered by Explorer/the taskbar at high DPI - smooth scaling is
the correct, expected look there, so QPainter's antialiasing stays ON
here, the one deliberate exception to that pixel-art rule, because the
CONTEXT is different, not because the rule was forgotten.

ICO FORMAT: Qt's own ICO writer, tested empirically, does not reliably
emit multiple embedded sizes into one file (repeated QImageWriter.
write() calls silently keep only the last one - confirmed by reading
the result back and finding a single frame). GRANICE forbids adding
Pillow as a new dependency for this. The ICO container format is
simple and well-documented (a directory of PNG-compressed entries,
supported natively since Windows Vista) - _write_ico() below hand-
assembles one with the stdlib `struct` module, no new dependency.
"""
import os
import struct

from PySide6.QtCore import QBuffer, QIODevice, QPointF, QRectF, Qt
from PySide6.QtGui import QColor, QImage, QPainter, QPainterPath
from PySide6.QtWidgets import QApplication

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(OUT_DIR, "..", "..", ".."))
SOURCE_LOGO = os.path.join(REPO_ROOT, "runtime", "epw_os", "resources", "about_logo.png")

# Found by inspecting runtime/epw_os/resources/about_logo.png directly
# (1254x1254) - the WHOLE navy plaque (top/bottom pinstripes, "EPW",
# the "ENTRY GATE SYSTEM" tagline), not just the lettering. First
# attempt cropped the letters alone and pasted them onto a hand-picked
# navy QColor for the surrounding badge - the two navies didn't match
# (the real plaque's own background is a different shade), leaving a
# visible rectangular seam. Second attempt used a looser crop of the
# whole plaque but still caught a few pixels of the plaque's own OUTER
# grey bezel/frame on the right edge (verified: sampling pixelColor()
# along each edge showed grey ~x370-392, clean navy only up to ~x365) -
# visible as a thin grey sliver once scaled up. This crop is trimmed
# to land inside the navy interior on all four sides (verified the
# same way, sampled pixel by pixel, not guessed) - self-consistent
# navy background, no seam, no stray bezel pixels.
_EPW_PLAQUE_CROP = (470, 242, 355, 168)  # x, y, w, h

# Icon frames embedded in the .ico files. 16/32/48/256 are the sizes
# Windows Explorer actually requests (small / details+taskbar / medium
# / extra-large); 128 is added for the in-between high-DPI scalings,
# rather than leaving Explorer to stretch 48 up to 256.
SIZES = (16, 32, 48, 128, 256)

# Standalone logo PNGs (the official logo as a usable asset - round,
# transparent outside the vignette). 256 is what studio/main.py's
# splash draws; 512 exists for anything printed or scaled up later.
LOGO_SIZES = (128, 256, 512)

# The two thresholds the module docstring explains. Both are "smallest
# size at which the full illustration still reads", measured on the
# real rendered output, and they differ because the two icons give the
# logo very different shares of their canvas.
_ILLUSTRATION_MIN_PX = 48   # app icon: logo fills ~92% of the canvas
_FILE_INSET_MIN_PX = 128    # file icon: logo fills ~55% of the canvas


def _load_source() -> QImage:
    source = QImage(SOURCE_LOGO)
    if source.isNull():
        raise SystemExit(f"Could not read source logo at {SOURCE_LOGO!r} - is runtime/ present?")
    return source


def _load_epw_crop() -> QImage:
    source = _load_source()
    x, y, w, h = _EPW_PLAQUE_CROP
    return source.copy(x, y, w, h)


def _load_circle_logo() -> QImage:
    """The whole logo, re-cut to its own circular vignette with an
    antialiased alpha edge (see "THE VIGNETTE" in this module's
    docstring - the circle is inscribed, so the crop is simply the
    largest centered square, which for a 1254x1254 source is the whole
    image). The black square corners become transparent, so the badge
    sits on whatever background Explorer, the taskbar or the splash
    happens to use instead of carrying a black box around."""
    source = _load_source()
    side = min(source.width(), source.height())
    square = source.copy(
        (source.width() - side) // 2, (source.height() - side) // 2, side, side
    )

    out = QImage(side, side, QImage.Format.Format_ARGB32)
    out.fill(Qt.GlobalColor.transparent)
    painter = QPainter(out)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing, True)

    # Mask first, illustration second, via SourceIn - NOT the other way
    # round with DestinationIn, which was the first attempt here and is
    # silently wrong: Qt composites only WITHIN the primitive being
    # drawn, so an ellipse drawn in DestinationIn mode leaves every
    # pixel OUTSIDE itself completely untouched - the black corners
    # survived in full (seen on the rendered contact sheet, which is
    # exactly why that sheet is generated). Painting an antialiased
    # disc into an empty image and then drawing the illustration in
    # SourceIn keeps the illustration only where the disc already put
    # alpha, corners included, and the disc's own antialiased rim
    # becomes the logo's rim - which a setClipPath() would not give
    # either (Qt clips drawImage on whole pixels, leaving a visibly
    # jagged edge once the result is scaled down).
    painter.setPen(Qt.PenStyle.NoPen)
    painter.setBrush(QColor(0, 0, 0, 255))
    painter.drawEllipse(QRectF(0.5, 0.5, side - 1.0, side - 1.0))
    painter.setCompositionMode(QPainter.CompositionMode.CompositionMode_SourceIn)
    painter.drawImage(0, 0, square)
    painter.end()
    return out


def _draw_circle_logo(painter: QPainter, rect: QRectF, circle_logo: QImage):
    """Fits the round logo inside `rect`, centered, never stretched."""
    target = max(1, round(min(rect.width(), rect.height())))
    scaled = circle_logo.scaled(
        target, target,
        Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation,
    )
    dx = rect.x() + (rect.width() - scaled.width()) / 2
    dy = rect.y() + (rect.height() - scaled.height()) / 2
    painter.drawImage(QPointF(dx, dy), scaled)


def _draw_plaque(painter: QPainter, rect: QRectF, epw_crop: QImage, border: bool = True):
    """Fills `rect` (rounded) by fitting the WHOLE `epw_crop` inside it
    (KeepAspectRatio - the plaque is ~2:1, rect is often square, so
    "cover" would crop real letters off the sides; tried that first,
    reverted - see this module's own docstring) and filling whatever
    margin is left with a color SAMPLED from the crop's own corner
    pixel (guaranteed to match - definitely background, never a
    letter), not a hand-picked QColor guess (that mismatch is exactly
    what the first version of this function got wrong)."""
    radius = rect.height() * 0.12
    path = QPainterPath()
    path.addRoundedRect(rect, radius, radius)
    background = epw_crop.pixelColor(0, 0)
    painter.fillPath(path, background)

    painter.save()
    painter.setClipPath(path)
    scaled = epw_crop.scaled(
        max(1, round(rect.width())), max(1, round(rect.height())),
        Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation,
    )
    dx = rect.x() + (rect.width() - scaled.width()) / 2
    dy = rect.y() + (rect.height() - scaled.height()) / 2
    painter.drawImage(QPointF(dx, dy), scaled)
    painter.restore()

    if border:
        pen = painter.pen()
        pen.setColor(QColor(220, 220, 220))
        pen.setWidthF(max(1.0, rect.height() * 0.015))
        painter.setPen(pen)
        painter.drawPath(path)


def _render_logo(size: int, circle_logo: QImage) -> QImage:
    """The official logo as a standalone asset: the whole illustration,
    round, transparent outside the vignette, nothing added."""
    img = QImage(size, size, QImage.Format.Format_ARGB32)
    img.fill(Qt.GlobalColor.transparent)
    painter = QPainter(img)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing, True)
    painter.setRenderHint(QPainter.RenderHint.SmoothPixmapTransform, True)
    _draw_circle_logo(painter, QRectF(0, 0, size, size), circle_logo)
    painter.end()
    return img


def _render_app_icon(size: int, epw_crop: QImage, circle_logo: QImage) -> QImage:
    """The application icon: the whole logo as a round badge at sizes
    where it reads, the plaque in a rounded square below that (see the
    two-tier explanation in this module's docstring)."""
    img = QImage(size, size, QImage.Format.Format_ARGB32)
    img.fill(Qt.GlobalColor.transparent)
    painter = QPainter(img)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing, True)
    painter.setRenderHint(QPainter.RenderHint.SmoothPixmapTransform, True)

    margin = max(1, round(size * 0.04))
    rect = QRectF(margin, margin, size - 2 * margin, size - 2 * margin)
    if size >= _ILLUSTRATION_MIN_PX:
        _draw_circle_logo(painter, rect, circle_logo)
    else:
        _draw_plaque(painter, rect, epw_crop)
    painter.end()
    return img


def _render_file_icon(size: int, epw_crop: QImage, circle_logo: QImage) -> QImage:
    """The .epw project-file icon - a document silhouette (same folded-
    top-right-corner shape as studio/shell/icons/new.png, redrawn here
    at real size instead of upscaled) carrying the logo in its lower
    two-thirds - "ma sie kojarzyc z DOKUMENTEM, nie z programem" (must
    read as a DOCUMENT, not the program) is exactly why this is a page
    shape carrying the badge, not the badge alone."""
    img = QImage(size, size, QImage.Format.Format_ARGB32)
    img.fill(Qt.GlobalColor.transparent)
    painter = QPainter(img)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing, True)
    painter.setRenderHint(QPainter.RenderHint.SmoothPixmapTransform, True)

    margin_x = size * 0.14
    margin_y = size * 0.06
    fold = size * 0.22
    page = QRectF(margin_x, margin_y, size - 2 * margin_x, size - 2 * margin_y)

    path = QPainterPath()
    path.moveTo(page.left(), page.top())
    path.lineTo(page.right() - fold, page.top())
    path.lineTo(page.right(), page.top() + fold)
    path.lineTo(page.right(), page.bottom())
    path.lineTo(page.left(), page.bottom())
    path.closeSubpath()
    painter.fillPath(path, QColor(255, 255, 255))
    painter.setPen(QColor(30, 30, 30))
    pen = painter.pen()
    pen.setWidthF(max(1.0, size * 0.012))
    painter.setPen(pen)
    painter.drawPath(path)

    fold_path = QPainterPath()
    fold_path.moveTo(page.right() - fold, page.top())
    fold_path.lineTo(page.right() - fold, page.top() + fold)
    fold_path.lineTo(page.right(), page.top() + fold)
    fold_path.closeSubpath()
    painter.fillPath(fold_path, QColor(210, 210, 210))
    painter.drawPath(fold_path)

    if size >= _FILE_INSET_MIN_PX:
        # The round logo, centered in the page's lower two-thirds and
        # sized to the page WIDTH (it is square, unlike the ~2:1
        # plaque, so it needs the room the plaque did not).
        diameter = page.width() * 0.68
        logo_rect = QRectF(
            page.left() + (page.width() - diameter) / 2,
            page.top() + page.height() * 0.26,
            diameter,
            diameter,
        )
        _draw_circle_logo(painter, logo_rect, circle_logo)
        badge_bottom = logo_rect.bottom()
    else:
        badge_rect = QRectF(
            page.left() + page.width() * 0.12,
            page.top() + page.height() * 0.40,
            page.width() * 0.76,
            page.height() * 0.42,
        )
        _draw_plaque(painter, badge_rect, epw_crop)
        badge_bottom = badge_rect.bottom()

    # A few "text lines" below the badge, same convention studio/shell/
    # icons/generate_icons.py's own icon_new() already uses for "this is
    # a document with content", scaled to size.
    line_y = badge_bottom + page.height() * 0.06
    line_h = max(1.0, size * 0.02)
    for i in range(2):
        y = line_y + i * (line_h * 2.2)
        if y + line_h > page.bottom() - page.height() * 0.04:
            break
        painter.fillRect(QRectF(page.left() + page.width() * 0.18, y, page.width() * 0.5, line_h), QColor(160, 160, 160))

    painter.end()
    return img


def _image_to_png_bytes(img: QImage) -> bytes:
    buffer = QBuffer()
    buffer.open(QIODevice.OpenModeFlag.WriteOnly)
    img.save(buffer, "PNG")
    data = bytes(buffer.data())
    buffer.close()
    return data


def _write_ico(path: str, images_by_size: dict):
    """Hand-assembled ICO container (PNG-compressed entries, native
    since Windows Vista) - see this module's own docstring for why Qt's
    own writer isn't used. `images_by_size`: {size: QImage}, largest
    last is NOT required (order in the file is irrelevant to Windows,
    which picks by requested size) but kept sorted here for a
    deterministic, diffable file."""
    sizes = sorted(images_by_size.keys())
    entries = []
    blobs = []
    offset = 6 + 16 * len(sizes)  # ICONDIR header + one ICONDIRENTRY per image
    for size in sizes:
        blob = _image_to_png_bytes(images_by_size[size])
        blobs.append(blob)
        dim_byte = 0 if size >= 256 else size  # 0 means "256" in ICO's own convention
        entries.append(struct.pack(
            "<BBBBHHII",
            dim_byte, dim_byte,  # width, height
            0, 0,                 # color count, reserved
            1, 32,                # planes, bit count
            len(blob), offset,
        ))
        offset += len(blob)

    with open(path, "wb") as f:
        f.write(struct.pack("<HHH", 0, 1, len(sizes)))  # ICONDIR: reserved, type=1 (icon), count
        for entry in entries:
            f.write(entry)
        for blob in blobs:
            f.write(blob)


def _write_contact_sheet(path: str, app_images: dict, file_images: dict, logo_images: dict):
    """Every generated frame at its real pixel size, side by side on the
    Studio panel grey, so the two-tier thresholds above can be CHECKED
    by looking rather than trusted - same convention studio/shell/icons/
    _contact_sheet.png already uses for the toolbar set."""
    pad = 16
    label_h = 18
    row_h = 256
    columns = sorted(set(app_images) | set(file_images) | set(logo_images))
    width = pad + sum(max(size, 48) + pad for size in columns)
    rows = [("app", app_images), ("file", file_images), ("logo", logo_images)]
    height = pad + len(rows) * (row_h + label_h + pad)

    sheet = QImage(width, height, QImage.Format.Format_ARGB32)
    sheet.fill(QColor("#D4D0C8"))  # STUDIO_UI_STANDARD.md's own panel_bg
    painter = QPainter(sheet)
    painter.setPen(QColor("#000000"))

    y = pad
    for name, images in rows:
        x = pad
        for size in columns:
            img = images.get(size)
            if img is not None:
                painter.drawImage(x, y + (row_h - img.height()), img)
            painter.drawText(
                QRectF(x, y + row_h + 2, max(size, 48), label_h),
                Qt.AlignmentFlag.AlignLeft,
                f"{name} {size}" if img is not None else f"{name} -",
            )
            x += max(size, 48) + pad
        y += row_h + label_h + pad
    painter.end()
    sheet.save(path, "PNG")


def generate_all():
    epw_crop = _load_epw_crop()
    circle_logo = _load_circle_logo()

    app_images = {size: _render_app_icon(size, epw_crop, circle_logo) for size in SIZES}
    file_images = {size: _render_file_icon(size, epw_crop, circle_logo) for size in SIZES}
    logo_images = {size: _render_logo(size, circle_logo) for size in LOGO_SIZES}

    for size, img in app_images.items():
        img.save(os.path.join(OUT_DIR, f"app_icon_{size}.png"), "PNG")
    for size, img in file_images.items():
        img.save(os.path.join(OUT_DIR, f"file_icon_{size}.png"), "PNG")
    for size, img in logo_images.items():
        img.save(os.path.join(OUT_DIR, f"logo_{size}.png"), "PNG")

    _write_ico(os.path.join(OUT_DIR, "app_icon.ico"), app_images)
    _write_ico(os.path.join(OUT_DIR, "file_icon.ico"), file_images)
    _write_contact_sheet(
        os.path.join(OUT_DIR, "_contact_sheet.png"), app_images, file_images, logo_images
    )

    print(f"generated app_icon_{{{','.join(map(str, SIZES))}}}.png + app_icon.ico")
    print(f"generated file_icon_{{{','.join(map(str, SIZES))}}}.png + file_icon.ico")
    print(f"generated logo_{{{','.join(map(str, LOGO_SIZES))}}}.png")
    print("generated _contact_sheet.png")


if __name__ == "__main__":
    app = QApplication.instance() or QApplication([])
    generate_all()
