"""Registers the .epw file extension with Windows Explorer (icon +
double-click-to-open) - task "fix/project-format-integrity" point 4.3.

⚠️ NOT RUN BY THIS SESSION. GRANICE: "NIE uruchamiaj go sam... Grzebanie
w rejestrze bez zgody to nie jest coś, co robi się w nocy." This file
exists so Waldek can review it and run it deliberately, on his own
machine, when he decides to - `python studio/tools/register_file_type.py`
(add `--uninstall` to remove exactly what this script added, nothing
else - see uninstall() below).

SCOPE, kept deliberately narrow:
- Writes ONLY under HKEY_CURRENT_USER\\Software\\Classes - the
  per-user registration area. Never touches HKEY_CLASSES_ROOT/
  HKEY_LOCAL_MACHINE (those need Administrator and affect every user
  on the machine) - a per-user file association needs neither, and
  "narrowest scope that achieves the goal" applies to the registry
  exactly as much as to code.
- Exactly one extension (.epw), exactly one ProgID ("EPWStudio.Project"),
  pointed at studio/shell/identity/file_icon.ico (task 4.3's own icon,
  generated by studio/shell/identity/generate_identity.py - never
  regenerated by this script) and at a launch command that runs
  studio/main.py with the double-clicked file as its one argument.
- uninstall() removes precisely the keys install() created - verified
  by construction (both walk the exact same _REGISTRY_PLAN list, one
  writing, one deleting), not a separate hand-maintained list that
  could drift from what was actually written.

This script does NOT make Studio actually READ a file path from
sys.argv on startup (studio/main.py's own main() takes none today) -
double-clicking a .epw file after running this would open Studio to
its usual new/blank project, not that file. Wiring "open this specific
project" through is a small, separate change to studio/main.py's own
argument handling, deliberately not made here - this task is "register
the association", not "teach Studio to accept a startup file", and
GRANICE's own "melduj etapami" means not quietly bundling a second,
unrequested change into a registry script.
"""
import sys
import winreg
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
STUDIO_DIR = TOOLS_DIR.parent
REPO_ROOT = STUDIO_DIR.parent

PROG_ID = "EPWStudio.Project"
EXTENSION = ".epw"
FILE_ICON_PATH = STUDIO_DIR / "shell" / "identity" / "file_icon.ico"
MAIN_SCRIPT = STUDIO_DIR / "main.py"

# Every registry value this script ever writes, in the order it writes
# them - (key_path, value_name_or_None_for_default, value). key_path is
# relative to HKEY_CURRENT_USER\Software\Classes. uninstall() deletes
# each of these KEYS entirely (a value is never the only thing in a key
# here, so removing the key is correct, not just clearing the value).
def _registry_plan(python_exe: str) -> list:
    open_command = f'"{python_exe}" "{MAIN_SCRIPT}" "%1"'
    return [
        (f"{EXTENSION}", None, PROG_ID),
        (f"{PROG_ID}", None, "Projekt EPW Studio"),
        (f"{PROG_ID}\\DefaultIcon", None, str(FILE_ICON_PATH)),
        (f"{PROG_ID}\\shell\\open\\command", None, open_command),
    ]


def install(python_exe: str = None) -> None:
    python_exe = python_exe or sys.executable
    if not FILE_ICON_PATH.exists():
        raise SystemExit(
            f"{FILE_ICON_PATH} nie istnieje - uruchom najpierw "
            f"studio/shell/identity/generate_identity.py."
        )
    for key_path, value_name, value in _registry_plan(python_exe):
        key = winreg.CreateKeyEx(winreg.HKEY_CURRENT_USER, f"Software\\Classes\\{key_path}")
        try:
            winreg.SetValueEx(key, value_name, 0, winreg.REG_SZ, value)
        finally:
            winreg.CloseKey(key)
    _notify_shell()
    print(f"Zarejestrowano {EXTENSION} -> {PROG_ID} (HKEY_CURRENT_USER\\Software\\Classes).")
    print(f"Ikona: {FILE_ICON_PATH}")
    print(f"Otwieranie: \"{python_exe}\" \"{MAIN_SCRIPT}\" \"<plik>\"")


def uninstall(python_exe: str = None) -> None:
    python_exe = python_exe or sys.executable
    for key_path, _value_name, _value in reversed(_registry_plan(python_exe)):
        try:
            winreg.DeleteKey(winreg.HKEY_CURRENT_USER, f"Software\\Classes\\{key_path}")
        except FileNotFoundError:
            pass  # already gone - not an error, uninstall is idempotent
    _notify_shell()
    print(f"Usunięto rejestrację {EXTENSION}/{PROG_ID} (HKEY_CURRENT_USER\\Software\\Classes).")


def _notify_shell() -> None:
    """Tells Explorer the file-association icon cache is stale, so the
    new/removed icon shows up without a manual refresh or logoff -
    SHChangeNotify(SHCNE_ASSOCCHANGED, SHCNF_IDLIST, None, None), the
    documented way to do this from a script, not a registry hack."""
    try:
        import ctypes
        SHCNE_ASSOCCHANGED = 0x08000000
        SHCNF_IDLIST = 0x0000
        ctypes.windll.shell32.SHChangeNotify(SHCNE_ASSOCCHANGED, SHCNF_IDLIST, None, None)
    except Exception as e:  # noqa: BLE001 - never fatal, just a "refresh now" nicety
        print(f"(Nie udało się odświeżyć powłoki automatycznie - {e}. "
              f"Zmiana zadziała mimo to, ale może wymagać wylogowania.)")


if __name__ == "__main__":
    if sys.platform != "win32":
        raise SystemExit("Ten skrypt rejestruje typ pliku w Windows - na innym systemie nic nie robi.")
    if "--uninstall" in sys.argv:
        uninstall()
    else:
        install()
