# Auto-generated by generate_help.py - do not edit by hand.
TOPICS = [
    ('welcome', 'EPW Studio', 'EPW Studio'),
    ('info', 'Informacje o projekcie', 'Project Information'),
    ('io_cards', 'Karty wejść/wyjść', 'I/O Cards'),
    ('locations', 'Lokalizacje', 'Locations'),
    ('points', 'Rejestr punktów', 'Point Registry'),
    ('apparatus', 'Rejestr aparatów', 'Apparatus Registry'),
    ('screens', 'Schemat synoptyczny', 'Synoptic Diagram'),
    ('logic', 'Logika', 'Logic'),
    ('zones', 'Strefy (Alarmówka)', 'Zones (Intrusion Alarm)'),
    ('lines', 'Linie dozorowe (Alarmówka)', 'Supervised Lines (Intrusion Alarm)'),
    ('protection_electrical', 'Zabezpieczenia elektryczne', 'Electrical Protection'),
    ('protection_process', 'Zabezpieczenia procesowe', 'Process Protection'),
    ('controller', 'Połączenie ze sterownikiem', 'Controller Connection'),
    ('devices', 'Skład urządzenia', 'Device Composition'),
    ('about', 'O programie EPW Studio', 'About EPW Studio'),
]
